<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAO5yXRN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAO5yXRN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAO5yXRN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAO5yXRN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAO5yXRN\App_KernelDevDebugContainer([
    'container.build_hash' => 'AO5yXRN',
    'container.build_id' => 'a3f2e449',
    'container.build_time' => 1757867429,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAO5yXRN');
